# Generated by Django 3.0.8 on 2021-05-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_projects_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
